### ISSUE TITLE
PyPDF2 is not built properly for Windows

### ISSUE THREAD

**Issue by bryanwweber** [conda-forge/pypdf2-feedstock#2]
Installing PyPDF2 using `conda install` results in a package directory (in `pkgs`) with only an `info` subdirectory, without the code. There is also no `pypdf2` directory in `site-packages` and `import PyPDF2` fails with an `ImportError`. I am having this problem on Windows 10, my `conda info` is

```
Current conda install:

             platform : win-64
        conda version : 4.1.12
    conda-env version : 2.5.2
  conda-build version : 2.0.1
       python version : 3.5.2.final.0
     requests version : 2.11.1
     root environment : C:\Users\user\AppData\Local\Continuum\Miniconda3  (writable)
  default environment : C:\Users\user\AppData\Local\Continuum\Miniconda3
     envs directories : C:\Users\user\AppData\Local\Continuum\Miniconda3\envs
        package cache : C:\Users\user\AppData\Local\Continuum\Miniconda3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
                        https://repo.continuum.io/pkgs/msys2/win-64/
                        https://repo.continuum.io/pkgs/msys2/noarch/
                        https://conda.anaconda.org/conda-forge/win-64/
                        https://conda.anaconda.org/conda-forge/noarch/
                        https://conda.anaconda.org/bryanwweber/channel/devel/win-64/
                        https://conda.anaconda.org/bryanwweber/channel/devel/noarch/
                        https://conda.anaconda.org/bryanwweber/win-64/
                        https://conda.anaconda.org/bryanwweber/noarch/
          config file : C:\Users\user\.condarc
         offline mode : False
    is foreign system : False
```

`pip install pypdf2` works properly.

**Comment by pmlandwehr** [comment]
we saw this problem with a different problem earlier - cc'ing @jakirkham ! Ticking the build number and doing a forced regeneration solved this the other time, so I'll try that here.

**Comment by jakirkham** [comment]
Thanks for letting us know @bryanwweber and raising to my attention @pmlandwehr. Went through the packages and found Windows packages for Python 3.5 64-bit, Python 3.5 32-bit, and Python 2.7 32-bit all suffered from this same problem. Have marked them all broken. The rest of the Windows packages appear to be fine.

Feel free to try rebuilding with a build number bump, @pmlandwehr, and please let me know how it goes.

**Comment by jakirkham** [comment]
Just looked at the new Windows packages and none of them appear to have this issue. Thanks everyone. If the issue resurfaces, please let us know.
